apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-service-with-auto-instrumentation
  namespace: sample-api
  labels:
    app: py-service-with-auto-instrumentation
spec:
  selector:
    matchLabels:
      app: py-service-with-auto-instrumentation
  replicas: 1
  template:
    metadata:
      labels:
        app: py-service-with-auto-instrumentation
      annotations:
        instrumentation.opentelemetry.io/inject-python: "o11y/my-instrumentation"
    spec:
      containers:
      - name: my-python-api-instrumented
        image: kodekloud/webapp-color:latest
        ports:
          - containerPort: 8080
            protocol: TCP